# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy PHP app to Azure Web App - deploy-laravel

on:
  push:
    branches:
      - deploy-azure
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    environment: cstsidbe2202502laraveldeploy

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.5'

      - name: Check if composer.json exists
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: 'composer.json'

      - name: Run composer install if composer.json exists
        if: steps.check_files.outputs.files_exists == 'true'
        run: composer validate --no-check-publish && composer install --prefer-dist --no-progress

      - name: Check if package.json exists
        id: check_npm_files
        uses: andstor/file-existence-action@v1
        with:
          files: 'package.json'

      - name: Run npm install if package.json exists
        if: steps.check_npm_files.outputs.files_exists == 'true'
        run: npm i

      - name: Run vite build
        env:
          VITE_API_URL: ${{ vars.VITE_API_HOST }}
          VITE_APP_ENV: ${{ vars.VITE_API_URL }}
        run: npm run build

      #ADICIONAR O PASSO DE ZIP NO BUILD, ANTES DO UPLOAD
      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: php-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: php-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_ECCD74EF9AF246C4A7C9119D18FC7FE5 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_ED4336CD1ADB4F1C92CF807830C5BCCE }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B6E8C5781FFA482DA0E63D61AF806286 }}

      #ADICIONAR O PASSO DE UNZIP NO DEPLOY, APOS O DOWNLOAD
      - name: unzip artifact for deployment
        run: unzip release.zip

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'deploy-laravel'
          slot-name: 'Production'
          package: .
